# Generated by Django 3.2.10 on 2022-04-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_auto_20220409_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('bollywood', 'bollywood'), ('coding', 'coding'), ('food', 'food')], max_length=50),
        ),
    ]
