# Generated by Django 3.2.10 on 2022-04-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0006_auto_20220409_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Bollywood', 'Bollywood'), ('food', 'food'), ('programming', 'programming'), ('Gate', 'Gate'), ('Cat', 'Cat'), ('IIT-JEE', 'IIT-JEE')], default='choices', max_length=200),
        ),
    ]
