# Generated by Django 3.2.10 on 2022-04-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0007_auto_20220409_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Bollywood', 'Bollywood'), ('food', 'food'), ('programming', 'programming'), ('Gate', 'Gate'), ('Cat', 'Cat'), ('IIT-JEE', 'IIT-JEE'), ('Hollywood', 'Hollywood')], default='coding', max_length=200),
        ),
    ]
