# Generated by Django 3.2.10 on 2022-04-10 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BlogApp', '0008_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='blog_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Bollywood', 'Bollywood'), ('Food', 'Food'), ('Programming', 'Programming'), ('Gate', 'Gate'), ('Cat', 'Cat'), ('IIT-JEE', 'IIT-JEE'), ('Hollywood', 'Hollywood'), ('friend', 'friend')], default='coding', max_length=200),
        ),
    ]
