# Generated by Django 3.2.10 on 2022-07-01 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BlogApp', '0012_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Bollywood', 'Bollywood'), ('Food', 'Food'), ('Programming', 'Programming'), ('Gate', 'Gate'), ('Cat', 'Cat'), ('IIT-JEE', 'IIT-JEE'), ('Hollywood', 'Hollywood'), ('friend', 'friend'), ('Painting', 'Painting')], default='coding', max_length=200),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
